services:
  web:
    image: nginx:alpine
    container_name: secureauth_web
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - secureauth_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  php:
    build: .
    container_name: secureauth_php
    volumes:
      - ./www:/var/www/html
      - ./data:/var/www/data
    environment:
      - FLAG_OBFUSCATED=QTBRTk9STlJNZzRYV0c4Z0Frb0FCa1ZHWEg1eFVBeGRVd0V0UUhJV0FScHNGQWNOQUFaY1hraz0=
    networks:
      - secureauth_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  secureauth_network:
    driver: bridge
